version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gotrue_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  gotrue:
    build: ./gotrue
    environment:
      - GOTRUE_JWT_SECRET=secret-key-shared-between-git-gateway-and-gotrue
      - GOTRUE_JWT_EXP=3600
      - GOTRUE_JWT_AUD=""
      - GOTRUE_DB_DRIVER=mysql
      - DATABASE_URL=gotrue:password@tcp(mysql_host:3306)/gotrue?parseTime=true&multiStatements=true
      - GOTRUE_API_HOST=0.0.0.0
      - PORT=8081
      - GOTRUE_SITE_URL=http://localhost:8080
      - GOTRUE_LOG_LEVEL=DEBUG
      - GOTRUE_OPERATOR_TOKEN=super-secret-operator-token
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_EXTERNAL_GITHUB_CLIENT_ID=${CLIENT_ID}
      - GOTRUE_EXTERNAL_GITHUB_SECRET=${CLIENT_SECRET}
      - GOTRUE_EXTERNAL_GITHUB_ENABLED=true
      - GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI=http://localhost:8085/.netlify/identity/callback
    ports:
      - 8080:8081

  git-gateway:
    image: asia.gcr.io/tomakako/git-gateway:20210511-1227
    environment:
      - GITGATEWAY_JWT_SECRET=secret-key-shared-between-git-gateway-and-gotrue
      - GITGATEWAY_DB_DRIVER=sqlite3
      - DATABASE_URL=gorm.db
      - GITGATEWAY_API_HOST=0.0.0.0
      - PORT=9999
      - GITGATEWAY_GITHUB_ACCESS_TOKEN=${GITGATEWAY_GITHUB_ACCESS_TOKEN}
      - GITGATEWAY_GITHUB_REPO=${GITGATEWAY_GITHUB_REPO}
    ports:
      - 8081:9999

  nginx:
    image: nginx:latest
    ports:
      - 8085:80
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html

  client_dev:
    build: ./client
    volumes:
      - ./:/app
      - /app/client/node_modules
    ports:
      - 8082:8080 
volumes:
  mysql-data:
  
