name: deploy git-gateway image to GCR and gotrue image to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: タグ用の変数生成
        run: |
          tag=$(TZ=Asia/Tokyo date +%Y%m%d-%H%M)
          echo "::set-output name=TAG::${tag}"
        id: tag-generator

      - uses: actions/checkout@v2

      - name: ghcrからgit-gatewayのビルド
        run: docker build -t git-gateway-image git-gateway
      - name: Google SDKのセットアップ
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: tomakako
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: gcrへのプッシュ
        run: |
          gcloud auth configure-docker --quiet
          docker tag git-gateway-image asia.gcr.io/tomakako/git-gateway:${{ steps.tag-generator.outputs.TAG }}
          docker push asia.gcr.io/tomakako/git-gateway:${{ steps.tag-generator.outputs.TAG }}

        - name: ghcrからgotrueのビルド
        run: docker build -t gotrue-image gotrue

      - name: Heroku Container Registryへのプッシュ
        run: |
          docker login --username=ohyama4z --password=${{ secrets.HEROKU_AUTH_TOKEN }} registry.heroku.com
          docker tag gotrue-image registry.heroku.com/kakomon-management-system/gotrue:${{ steps.tag-generator.outputs.TAG }}
          docker push registry.heroku.com/kakomon-management-system/gotrue:${{ steps.tag-generator.outputs.TAG }}

      
